[package]
name = "vibecoin"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
bitcoin = "0.32.6"
rand = "0.8"
tokio = { version = "1", features = ["net", "rt-multi-thread", "io-util", "macros"] }
